apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: skvrtmiko-go 
  janus-idp.io/tekton: skvrtmiko-go
  backstage.io/kubernetes-id: skvrtmiko-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: skvrtmiko-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml